package config

import (
	"path/filepath"
)

var (
	HOST_POST                        = "HOST_POST"
	HOST_POST_DEFAULT_VALUE          = ":8080"
	PROFILE                          = "PROFILE"
	PROFILE_DEFAULT_VALUE            = "default"
	SOURCE_FOLDER_NAME               = "SOURCE_FOLDER_NAME"
	SOURCE_FOLDER_NAME_DEFAULT_VALUE = filepath.Join("pkg", "app")

	FUND_TRANSFERS_DATASOURCE_USERNAME = "FUND_TRANSFERS_DATASOURCE_USERNAME"
	FUND_TRANSFERS_DATASOURCE_PASSWORD = "FUND_TRANSFERS_DATASOURCE_PASSWORD"
	FUND_TRANSFERS_DATASOURCE_URL      = "FUND_TRANSFERS_DATASOURCE_URL"
)
